### ISSUE TITLE
Firmware 20190608 (default) - stick hangs

### ISSUE THREAD

**Issue by DubhAd** [Koenkk/Z-Stack-firmware#105]
Running Z2M 1.5.1, with a CC2531 on the 20190608 (Default) firmware, I'm running into an odd problem. Every so often (5 days to a couple of weeks) the stick stops responding, everything goes offline, and I have to unplug and reconnect it, then restart Z2M.

I didn't see this problem on the previous (20190425) firmware, though I did have stability issues.

It _looks_ to be a firmware issue, but I'm not finding anybody else reporting the problem, and there's no newer firmware to upgrade to.

**Comment by Koenkk** [comment]
Could you try with: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing (doesn't need repairing).

**Comment by DubhAd** [comment]
Thanks. I'll give that a shot

**Comment by DubhAd** [comment]
Flashed, did result in a few devices (most annoying being the Gledopto LED controller) dropping off the mesh until I moved some Ikea routers around. I'll update with progress.

**Comment by DubhAd** [comment]
Nope, didn't help :(

**Comment by Koenkk** [comment]
Do you use one of the following features? 
- Availability
- Reporting
- Networkmap

**Comment by DubhAd** [comment]
I do use NetworkMap and Availability, but not Reporting.

I can disable any or all of those if it'll help stability.

**Comment by Koenkk** [comment]
Yes please try that. (especially the networkmap).

**Comment by DubhAd** [comment]
I disabled them both shortly after I'd posted, so we'll see how it goes.

Thanks

For reference, my config is now:

```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.2.30'
  user: some_user
  password: some_secret
serial:
  port: /dev/ttyACM0
advanced:
  pan_id: 0xdead
  ext_pan_id: [0xde, 0xad, 0xbe, 0xef, 0xca, 0xfe, 0x01, 0x02]
  channel: 25
  cache_state: true
  network_key: [0xde, 0xad, 0xbe, 0xef, 0xca, 0xfe, 0x01, 0x02, 0xde, 0xad, 0xbe, 0xef, 0xca, 0xfe, 0x01, 0x02]
  last_seen: 'ISO_8601'
  report: false
devices: devices.yaml
groups: groups.yaml
device_options:
  occupancy_timeout: 70
  humidity_precision: 1
  temperature_precision: 1
  retain: true
```
